import type { Metadata } from "next";

import { Rubik } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import { Footer } from "./components/Footer";

import { Providers } from "./provider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GameAffinity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          <Header />
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
