import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Header from "./components/Header";
import MainLayout from "./components/MainLayout";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GameAffinity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          <Header />
            {children}
        </Providers>
      </body>
    </html>
  );
}
